name: Package and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for tags
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      
      - name: Set up CMake
        uses: lukka/get-cmake@latest
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev
      
      - name: Prepare thirdparty dependencies
        run: |
          chmod +x thirdparty/download.sh
          ./thirdparty/download.sh
      
      - name: Build and package
        run: |
          chmod +x package.sh
          ./package.sh
          
      - name: Get package info
        id: package-info
        run: |
          PACKAGE_NAME="hdfs-client-cpp"
          VERSION="1.0.0"
          echo "package_name=${PACKAGE_NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "artifact=${PACKAGE_NAME}-${VERSION}.tar.gz" >> $GITHUB_OUTPUT
          echo "Checking if file exists:"
          ls -la package/
          if [ -f "package/${PACKAGE_NAME}-${VERSION}.tar.gz" ]; then
            echo "Package file exists and is ready for upload"
          else
            echo "ERROR: Package file not found!"
            exit 1
          fi
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Create release if not exists
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: HDFS Client Cpp Distribution
          tag_name: hdfs-client-cpp-dist
          draft: false
          prerelease: false
          generate_release_notes: false
          body: |
            HDFS Client Distribution Package - Updated on ${{ steps.date.outputs.date }}
            
            This is an automatically updated release containing the latest build of the HDFS client.
          files: |
            package/${{ steps.package-info.outputs.artifact }}
